export const paths = {
  auth: {
    root: '/auth',
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    otp: '/auth/otp',
    terms: '/auth/terms',
    privacy: '/auth/privacy',
  },
  manager: {
    root: '/manager',
    home: '/manager/home',
    inventory: '/manager/inventory',
    facilities: '/manager/facilities',
    employees: '/manager/employees',
    employeeDetail: (id: string) => `/manager/employees/${id}`,
    attendance: '/manager/attendance',
    attendanceCheckIn: '/manager/attendance/check-in',
    attendanceManagement: '/manager/attendance/management',
    hazardObservations: '/manager/hazard-observations',
    housekeeping: '/manager/housekeeping',
    contacts: '/manager/contacts',
    itTickets: '/manager/it-tickets',
    expeditions: '/manager/expeditions',
    requests: '/manager/requests',
    requestNew: '/manager/requests/new',
    requestDetail: (id: string) => `/manager/requests/${id}`,
    profile: '/manager/profile',
  },
  employee: {
    root: '/employee',
    home: '/employee/home',
    inventory: '/employee/inventory',
    facilities: '/employee/facilities',
    attendance: '/employee/attendance',
    hazardObservations: '/employee/hazard-observations',
    housekeeping: '/employee/housekeeping',
    contacts: '/employee/contacts',
    itTickets: '/employee/it-tickets',
    expeditions: '/employee/expeditions',
    requests: '/employee/requests',
    requestNew: '/employee/requests/new',
    requestDetail: (id: string) => `/employee/requests/${id}`,
    profile: '/employee/profile',
  },
};
