export const paths = {
  auth: {
    root: '/auth',
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    otp: '/auth/otp',
    terms: '/auth/terms',
    privacy: '/auth/privacy',
  },
  manager: {
    root: '/manager',
    home: '/manager/home',
    inventory: '/manager/inventory',
    facilities: '/manager/facilities',
    employees: '/manager/employees',
    employeeDetail: (id: string) => `/manager/employees/${id}`,
    attendance: '/manager/attendance',
    attendanceCheckIn: '/manager/attendance/check-in',
    attendanceManagement: '/manager/attendance/management',
    hazardObservations: '/manager/hazard-observations',
    contacts: '/manager/contacts',
  },
  employee: {
    root: '/employee',
    home: '/employee/home',
    inventory: '/employee/inventory',
    facilities: '/employee/facilities',
    attendance: '/employee/attendance',
    hazardObservations: '/employee/hazard-observations',
    contacts: '/employee/contacts',
  },
};
